[project]
name = "toDoTicketsWeb"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "jinja2",
  "sqlalchemy>=2.0",
  "pydantic>=2.0",
  "weasyprint",
  "python-cups",
]

[tool.uvicorn]
factory = false
host = "0.0.0.0"
port = 8080
